[[redirects]]
  from = "/guide/"
  to = "/guide/introduction.html"

[[redirects]]
 from = "guide/doc-style-guide.html"
 to = "/guide/contributing/doc-style-guide.html"

[[redirects]]
  from = "/guide/writing-guide.html"
  to = "/guide/contributing/writing-guide.html"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  publish = "src/.vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build"
